// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwk7GSH6SmmHL8x2tkT23r70gEH5X2Wt4',
    appId: '1:312257051181:web:427eaa1a6bb63d783796a4',
    messagingSenderId: '312257051181',
    projectId: 'mynotes-vishesh',
    authDomain: 'mynotes-vishesh.firebaseapp.com',
    storageBucket: 'mynotes-vishesh.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ_72zjtGJ8rpfReFn-wGloNuTjmfTlHw',
    appId: '1:312257051181:android:ccd4d11606230cd93796a4',
    messagingSenderId: '312257051181',
    projectId: 'mynotes-vishesh',
    storageBucket: 'mynotes-vishesh.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8sOIN-lJgzXA18nqDmGX-BjNTmpuWMkw',
    appId: '1:312257051181:ios:226de2070ee532e73796a4',
    messagingSenderId: '312257051181',
    projectId: 'mynotes-vishesh',
    storageBucket: 'mynotes-vishesh.appspot.com',
    iosBundleId: 'com.doit.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8sOIN-lJgzXA18nqDmGX-BjNTmpuWMkw',
    appId: '1:312257051181:ios:226de2070ee532e73796a4',
    messagingSenderId: '312257051181',
    projectId: 'mynotes-vishesh',
    storageBucket: 'mynotes-vishesh.appspot.com',
    iosBundleId: 'com.doit.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwk7GSH6SmmHL8x2tkT23r70gEH5X2Wt4',
    appId: '1:312257051181:web:92de070ce7ccfa523796a4',
    messagingSenderId: '312257051181',
    projectId: 'mynotes-vishesh',
    authDomain: 'mynotes-vishesh.firebaseapp.com',
    storageBucket: 'mynotes-vishesh.appspot.com',
  );
}
